OPENAI_API_KEY = "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"

base_dir = "/mnt/d/AI4EIC-2023/AI4EICHackathon-app/streamlit_leaderboard"
UserInfoDir = "/mnt/d/AI4EIC-2023/AI4EICHackathon-app/streamlit_leaderboard/UserInfo"
UserInfoFile = "/mnt/d/AI4EIC-2023/AI4EICHackathon-app/streamlit_leaderboard/UserInfo/users.yaml"
[passwords]
Team1_user1 = "AI4EIC"
Team1_user2 = "AI4EIC"
Team2_user3 = "AI4EIC"
Team2_user4 = "AI4EIC"
