OPENAI_API_KEY = "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"
TRUBRICS_EMAIL = "jgiroux@wm.edu"
TRUBRICS_PASSWORD = "J!mmyg1062"

base_dir = "/mnt/d/AI4EIC-2023/AI4EICHackathon-app/Final-version/AI4EICHackathon2023-Streamlit/streamlit_leaderboard"
UserInfoDir = "/mnt/d/AI4EIC-2023/AI4EICHackathon-app/Final-version/AI4EICHackathon2023-Streamlit/streamlit_leaderboard/UserInfo"
UserInfoFile = "/mnt/d/AI4EIC-2023/AI4EICHackathon-app/Final-version/AI4EICHackathon2023-Streamlit/streamlit_leaderboard/UserInfo/users.yaml"
[passwords]
Team1_user1 = "AI4EIC"
Team1_user2 = "AI4EIC"
Team2_user3 = "AI4EIC"
Team2_user4 = "AI4EIC"
Team3_user5 = "AI4EIC"
Team3_user6 = "AI4EIC"
Team4_user7 = "AI4EIC"
Team4_user8 = "AI4EIC"
Team5_user9 = "AI4EIC"
Team5_user10 = "AI4EIC"
Team6_user11 = "AI4EIC"
Team6_user12 = "AI4EIC"
